### ISSUE TITLE
Improve answer accuracy of wordquiz in bot2

### ISSUE THREAD

**Issue by cubistplay** [Fumire/FumireBots#2]
Currently answer accuracy calculates percentage of correct graphemes.
But I think initial graphemes (초성) should not be included while calculating answer accuracy.
It distracts players and answer accuracy cannot be lower than 33% for now.

**Comment by Fumire** [comment]
This case has been accepted as the commit c304295fa98d9ce9c29f2a5dca497baa22af82c1
