### ISSUE TITLE
[Bot2] Space characters are hardly recognizable in typing game

### ISSUE THREAD

**Issue by cubistplay** [Fumire/FumireBots#6]
![image](https://user-images.githubusercontent.com/31873152/102737326-786eb080-438a-11eb-85bf-f800a2e77bf1.png)

Space characters are hardly recognizable especially trailing space.
Inserting 'V' instead of trailing space character would be great.

**Comment by Fumire** [comment]
How about this character (**␣**) instead?

**Comment by cubistplay** [comment]
That could work either.

**Comment by Fumire** [comment]
Finally, the space characters are replaced by `·` because of font
